version: "3.9"

services:
  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile
    depends_on: 
      - pgdb
    ports:
      - 5000:5000
    restart: always
    env_file:
      - ./postgres.env


  pgdb:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./postgres.env
    volumes:
      - ./dist/:/var/lib/postgresql/data
      - ./rest/tables.sql:/docker-entrypoint-initdb.d/init.sql
    